services:
  aaacet_nginx:
    container_name: "AAACET_LoadBalancer"
    image: "nginx:latest"
    volumes: 
      - ../volumes/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../volumes/nginx/snippets/:/etc/nginx/snippets/
      - ../volumes/static/:/var/www/static/
    networks:
      default:
        ipv4_address: 10.1.0.11

  api:
    container_name: "AAACET_Api"
    build: 
      context: './api/'
      dockerfile: 'Dockerfile'
    stop_signal: SIGKILL
    depends_on:
      - db
    networks:
      default:
        ipv4_address: 10.1.0.12

  db:
    container_name: 'AAACET_DB'
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'Avesso22@'
      MYSQL_DATABASE: aaacet
      MYSQL_USER: aaacet
      MYSQL_PASSWORD: 'Avesso22@'
    restart: on-failure
    volumes:
     - ../volumes/database/mariadb/:/var/lib/mysql
     - ../volumes/database/init.sql:/docker-entrypoint-initdb.d/1.sql

networks:
  default:
    external:
      name: external-network
